#!/bin/bash
#
# mk_doc.sh
#
# libsrt documentation generation
#
# Copyright (c) 2015-2016 F. Aragon. All rights reserved.
#

if [ $# != 2 ] ; then
	echo "Syntax: $0 src_path out_path" >&2
	echo "Example: $0 src out_doc" >&2
	exit 1
fi

SRC_PATH=$1
DOC_PATH_OUT=$2
ERRORS=0
mkdir "$DOC_PATH_OUT" 2>/dev/null

if [ ! -e "$DOC_PATH_OUT" ] ; then
	echo "Path $1 not found" >&2
	exit 2
fi

INDEX="$DOC_PATH_OUT/libsrt.html"

C2DOC_PY=$(echo $0 | sed 's/mk_doc.sh/c2doc.py/g')

if [ "$C2DOC_PY" == "$0" ] ; then
	echo "Error: this file name must be 'mk_doc.sh'"
	exit 1
fi

echo "<!DOCTYPE html><html><meta http-equiv=\"Content-Type\" content=\"text/"\
     "html; charset=latin1\"><title>libsrt</title><body><h3><a"\
     "href="https://github.com/faragon/libsrt">libsrt</a> documentation"\
     "</h3><br><br>This documentation has been generated by $0 (which calls"\
     "$C2DOC_PY). Information is retrieved from #API sections in .h files."\
     "If you don't like how documentation is rendered, or"\
     "having any suggestion, your observations are very welcome.<br><br>"\
     > "$INDEX"
for i in $SRC_PATH/*\.h ; do
	II=$(echo $i | sed 's/\/\//\//g')
	TGT=$(echo $i | awk -F '/' '{print $NF}')
	echo -n "$II: " >&2
	if $C2DOC_PY "Documentation for $TGT" < "$i" >"$DOC_PATH_OUT/$TGT.html"
	then
		echo "OK" >&2
		if (( $(wc -l <"$DOC_PATH_OUT/$TGT.html") > 2 )) ; then
			echo '<br><a href="'"$TGT.html"'">'"$TGT"'</a><br>' \
				>> "$INDEX"
		fi
	else	ERRORS=$((ERRORS + 1))
	fi
done
echo '</table></body></html>' >> "$INDEX"

exit $ERRORS

